const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const userInfoRouter = require('./userInfoRouter')
const authRouter = require('./authRouter')
const ResultRouter = require('./ResultsRouter')
const TeamRouter = require('./TeamRouter')
const CompetitionRouter = require('./CompetitionRouter')
const CompetitionAdminsRouter = require('./CompetitionAdminsRouter')
const TeammembersRouter = require('./TeamMembersRouter')
const AdressRouter = require('./AdressRouter')
const ApplicationRouter = require('./ApplicationRouter')
const CompetitionRegionRouter = require('./CompetitionRegionRouter')
const DisciplineRouter = require('./DisciplineRouter')
const ProjectsRouter = require('./ProjectsRouter')
const RegionsRouter = require('./RegionsRouter')
const analyticsRouter = require('./analyticsRouter')
const CompetitionResultRouter = require('./CompetitionResultRouter')
const InvitationRouter = require('./InvitationRouter')
const MigrationRouter = require('./MigrationRouter')

router.use('/auth', authRouter)
router.use('/user', userRouter)
router.use('/userInfo', userInfoRouter)
router.use('/analytics', analyticsRouter)
router.use('/results', ResultRouter)
router.use('/teams', TeamRouter)
router.use('/competitions', CompetitionRouter)
router.use('/competition-admins', CompetitionAdminsRouter)
router.use('/team-members', TeammembersRouter)
router.use('/address', AdressRouter)
router.use('/applications', ApplicationRouter)
router.use('/competition-region', CompetitionRegionRouter)
router.use('/disciplines', DisciplineRouter)
router.use('/projects', ProjectsRouter)
router.use('/regions', RegionsRouter)
router.use('/competition-results', CompetitionResultRouter)
router.use('/invitations', InvitationRouter)
router.use('/migration', MigrationRouter)

module.exports = router
