const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const userInfoRouter = require('./userInfoRouter')
const ResultRouter = require('./ResultsRouter')
const TeamRouter = require('./ResultsRouter')
const CompetitionRouter = require('./ResultsRouter')
const CompetitionAdminsRouter = require('./ResultsRouter')
const TeammembersRouter = require('./ResultsRouter')
const AdressRouter = require('./ResultsRouter')
const ApplicationRouter = require('./ApplicationRouter')
const CompetitionRegionRouter = require('./CompetitionRegionRouter')
const DisciplineRouter = require('./DisciplineRouter')
const ProjectsRouter = require('./ProjectsRouter')
const RegionsRouter = require('./RegionsRouter')

router.use('/user', userRouter)
router.use('/userInfo', userInfoRouter)

router.use('/result', ResultRouter)
router.use('/team', TeamRouter)
router.use('/competirion', CompetitionRouter)
router.use('/CompetitionAdmins', CompetitionAdminsRouter)
router.use('/TeamMembers', TeammembersRouter)
router.use('/adress', AdressRouter)
router.use('/application', ApplicationRouter)
router.use('/CompetitionRegion', CompetitionRegionRouter)
router.use('/Discipline', DisciplineRouter)
router.use('/Regions', RegionsRouter)

module.exports = router
